simple calculator
airatbikbaev/geekbrains-go pull request #2
Opened 2020-12-02 17:29 UTC by airatbikbaev

2020-12-06 13:12 UTC, rumyantseva requested changes
Предлагаю немного доработать PR: добавить побольше обратной связи для пользователя и исправить недопустимые арифместические операции,  а также расчет a^b для b < 0.

2020-12-06 13:12 UTC, rumyantseva commented on hw2/main.go
> +			continue
Тут было бы не плохо выводить для пользователя какую-то обратную связь о том, что произошла ошибка и введенное значение не является Float'ом.

2020-12-06 13:12 UTC, rumyantseva commented on hw2/main.go
> +		case "/":
Что будет при `b == 0`?

2020-12-06 13:12 UTC, rumyantseva commented on hw2/main.go
> +		case "%":
Вообще, если a и b не целые, то скорее такая операция недопустима. Лучше честно сообщать пользователю о том, что взятие остатка возможно только для целых, а не преобразовывать числа с плавающей точкой. Уж слишком неточный результат получится. Например, какой остаток от деления 5.6 на 3.2? Никакой :) Для чисел с плавающей точкой эта арифметическая операция недостима.

2020-12-06 13:12 UTC, rumyantseva commented on hw2/main.go
> +		case "^":
Что будет, если b - отрицательное число?

2020-12-06 13:12 UTC, rumyantseva commented on hw2/main.go
> +			continue
Опять же здесь нужна обратная связь о том, что ввели неподдерживаемую операцию.

2020-12-08 18:05 UTC, airatbikbaev commented on hw2/main.go
> +		case "%":
С математикой и обратной связью пользователю все понятно)
Пока оставлю как есть, так как со временем не очень сейчас

2020-12-08 18:05 UTC, merged

2020-12-08 18:20 UTC, rumyantseva commented on hw2/main.go
> +		case "%":
Окей :) Если прям очень хочется для чисел с плавающей точкой такой остаток считать, то можно одну из функцйи библиотеки math взять. Но я бы для простоты может быть просто не стала это здесь делать :)